# Generated by Django 4.1.1 on 2022-12-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_tour_alter_product_tour_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tour',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='tour_policy',
            field=models.CharField(max_length=10000),
        ),
    ]
