# Generated by Django 4.1.1 on 2022-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='category_id',
            field=models.CharField(max_length=255),
        ),
    ]
