# Generated by Django 4.1.1 on 2022-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
