# Generated by Django 4.1.1 on 2022-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryList',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
