# Generated by Django 4.1.1 on 2022-12-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_category_createdat_alter_category_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryList',
        ),
    ]
